name: Feature request
description: Suggest an idea
labels: ["enhancement", "status:triage"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: Describe the feature and the problem it solves.
    validations:
      required: true
